"""Result types for AutoHDR Stage 1 (OCR-Assisted Damage Localization)."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, List


BBox = List[int]


@dataclass
class Stage1Event:
    """A progress boundary emitted while running the Stage 1 generator."""

    phase: str


@dataclass
class Stage1Result:
    """All localization and ordering products generated by Stage 1.

    The field names intentionally distinguish the two detector outputs from
    the fused output.  ``normal_boxes`` is the subset of OCR detector boxes
    retained after IoU fusion; ``fused_boxes`` is what enters reading order.
    """

    original_image: Any
    inverted_image: Any
    grayscale_image: Any
    inverted_image_path: str
    image_height: int
    image_width: int

    damage_boxes: List[BBox]
    ocr_boxes: List[BBox]
    normal_boxes: List[BBox]
    fused_boxes: List[BBox]
    ordered_boxes: List[BBox]

    num_normal: int
    num_damaged: int
