"""Result types for the Sino-Nôm character detection pipeline."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, List


BBox = List[int]


@dataclass
class DetectionEvent:
    """A progress boundary emitted while running character detection."""

    phase: str


@dataclass
class DetectionResult:
    """All localization and ordering products generated by character detection.

    The field names intentionally distinguish the two detector outputs from
    the fused output.  ``normal_boxes`` is the subset of OCR detector boxes
    retained after IoU fusion; ``fused_boxes`` is what enters reading order.
    """

    original_image: Any
    inverted_image: Any
    grayscale_image: Any
    inverted_image_path: str
    image_height: int
    image_width: int

    damage_boxes: List[BBox]
    ocr_boxes: List[BBox]
    normal_boxes: List[BBox]
    fused_boxes: List[BBox]
    ordered_boxes: List[BBox]

    num_normal: int
    num_damaged: int
